# Generated by Django 3.2.12 on 2022-05-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('El', 'Electronics'), ('Re', 'Real Estate'), ('Bk', 'Books'), ('He', 'Health'), ('Ga', 'Gadgets'), ('Co', 'Cosmetics'), ('Ag', 'Agri products'), ('Ww', 'Women wear'), ('Mw', 'Men wear'), ('Kw', 'Kids wear')], max_length=2)),
                ('item_description', models.CharField(max_length=250)),
                ('item_price', models.FloatField()),
                ('item_disc_price', models.FloatField(blank=True)),
                ('item_image', models.ImageField(default='default.jpg', upload_to='product_img')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitaa.items')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(to='Kitaa.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
