# Generated by Django 3.2.12 on 2022-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kitaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_disc_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
